### Machine Learning Pipeline

The dataset used for this example is obtained from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/dataset/222/bank+marketing).

The second part consists of creating a machine learning model to predict if the client will subscribe (yes/no) a term deposit (variable y).

#### Import Dataset

In [ ]:
# !pip install pandas joblib scikit-learn

Requirement already satisfied: pandas in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: joblib in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (1.5.3)
Requirement already satisfied: scikit-learn in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.26.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [ ]:
# import libraries
import pandas as pd
import joblib
import sklearn
print(sklearn.__version__)
LogisticRegression().get_params()
#print(params)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import f1_score

1.8.0
{'max_iter': 1000}

In [101]:
# read dataset
df = pd.read_csv("datasets/bank-full_train_test.csv")

In [102]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,29,housemaid,married,primary,no,0,yes,no,cellular,15,jul,317,3,-1,0,unknown,no
1,57,management,divorced,secondary,no,396,no,no,cellular,12,aug,108,2,-1,0,unknown,no
2,54,blue-collar,married,primary,no,714,no,no,cellular,5,may,225,1,-1,0,unknown,no
3,52,services,married,secondary,no,2072,no,no,cellular,10,jul,224,1,-1,0,unknown,no
4,34,management,married,tertiary,no,1778,no,no,cellular,4,nov,358,1,162,2,failure,yes

#### Transform Dataset

In [103]:
# balance dataset
def balance_dataset(df: pd.DataFrame) -> pd.DataFrame:
    # Separate the classes
    df_y0 = df[df['y'] == 'no']
    df_y1 = df[df['y'] == 'yes']

    # Find the smaller class size
    min_size = len(df_y1)

    # Randomly sample from each class
    df_y0_balanced = df_y0.sample(n=min_size, random_state=42)

    # Concatenate back together
    df_balanced = pd.concat([df_y0_balanced, df_y1])

    # Shuffle the dataset
    df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

    return df_balanced

df = balance_dataset(df)

In [104]:
df["y"] = (
    df["y"]
    .astype(str)
    .str.lower()
    .map({"yes": 1, "no": 0})
    .astype("int64")
)

In [105]:
# map target
df.loc[df["y"] == "yes", "y"] = 1
df.loc[df["y"] == "no", "y"] = 0
df["y"] = df["y"].astype(int)

In [106]:
# prepare dataset for classification model
class Transformer:
    def __init__(self):
        self.DROP_COLUMNS = []
        self.BINARY_FEATURES = [
            "housing",
            "loan",
            "default",
        ]

    def transform(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.drop(self.DROP_COLUMNS, axis=1)
        df = self._map_binary_column_to_int(df)
        df = self._map_month_to_int(df)

        return df

    def _map_binary_column_to_int(self, df: pd.DataFrame) -> pd.DataFrame:
        for col in self.BINARY_FEATURES:
            df[col] = df[col].map({"yes": 1, "no": 0})
        return df

    def _map_month_to_int(self, df: pd.DataFrame) -> pd.DataFrame:
        month_mapping = {
            "jan": 1,
            "feb": 2,
            "mar": 3,
            "apr": 4,
            "may": 5,
            "jun": 6,
            "jul": 7,
            "aug": 8,
            "sep": 9,
            "oct": 10,
            "nov": 11,
            "dec": 12,
        }
        df["month"] = df["month"].map(month_mapping)

        return df

In [107]:
# transform the dataset
df = Transformer().transform(df)

In [108]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,43,blue-collar,married,primary,0,50,0,0,unknown,28,5,90,8,-1,0,unknown,0
1,32,technician,single,secondary,0,40,0,0,cellular,8,8,419,2,-1,0,unknown,1
2,32,self-employed,single,tertiary,0,2559,0,0,cellular,7,7,889,1,-1,0,unknown,1
3,23,student,single,secondary,0,480,0,0,cellular,9,2,742,2,182,1,failure,1
4,32,management,single,tertiary,0,1169,1,0,unknown,21,5,322,2,-1,0,unknown,0

In [109]:
# encode categorical variables
ONE_HOT_ENCODE_COLUMNS = [
            "marital",
            "job",
            "education",
            "poutcome",
            "contact",
        ]

encoder = OneHotEncoder(drop='first', sparse_output=False).set_output(transform="pandas")
encoder.fit(df[ONE_HOT_ENCODE_COLUMNS])
encoded_df = encoder.transform(df[ONE_HOT_ENCODE_COLUMNS])
df = df.drop(columns=ONE_HOT_ENCODE_COLUMNS)
df = pd.concat([df, encoded_df], axis=1)

In [110]:
# save encoder - future use
joblib.dump(encoder, 'model_utils/encoder.pkl')

['model_utils/encoder.pkl']

In [111]:
df.head()

,age,default,balance,housing,loan,day,month,duration,campaign,pdays,...,job_unemployed,job_unknown,education_secondary,education_tertiary,education_unknown,poutcome_other,poutcome_success,poutcome_unknown,contact_telephone,contact_unknown
0,43,0,50,0,0,28,5,90,8,-1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,32,0,40,0,0,8,8,419,2,-1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,32,0,2559,0,0,7,7,889,1,-1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,23,0,480,0,0,9,2,742,2,182,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,32,0,1169,1,0,21,5,322,2,-1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0

#### Train and evaluate model

In [112]:
# Split the data into training and test sets
X = df.drop('y', axis=1)
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [113]:
# Define the model hyperparameters
params = {
    "solver": "lbfgs",
    "max_iter": 1000,
    "multi_class": "auto",
    "random_state": 8888,
}

print(params)

{'solver': 'lbfgs', 'max_iter': 1000, 'multi_class': 'auto', 'random_state': 8888}

In [114]:
from sklearn.linear_model import LogisticRegression

params = {
    "max_iter": 1000
}

print(params)
print(type(params))

lr = LogisticRegression(**params)

{'max_iter': 1000}
<class 'dict'>

In [115]:
lr.fit(X_train, y_train)

/Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [116]:
# Predict on the test set
y_pred = lr.predict(X_test)

In [117]:
# Calculate metrics
f1_score = f1_score(y_test, y_pred)

### MLFlow Integration

In [118]:
import sys
!{sys.executable} -m pip install mlflow

Requirement already satisfied: mlflow in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (3.12.0)
Requirement already satisfied: mlflow-skinny==3.12.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (3.12.0)
Requirement already satisfied: mlflow-tracing==3.12.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (3.12.0)
Requirement already satisfied: Flask-CORS<7 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (6.0.2)
Requirement already satisfied: Flask<4 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (3.13.5)
Requirement already satisfied: alembic!=1.10.0,<2 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (46.0.7)
Requirement already satisfied: docker<8,>=4.0.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<26 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (25.3.0)
Requirement already satisfied: huey<3,>=2.5.4 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (3.10.9)
Requirement already satisfied: numpy<3 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (2.4.4)
Requirement already satisfied: pandas<3 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (23.0.1)
Requirement already satisfied: scikit-learn<2 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (1.8.0)
Requirement already satisfied: scipy<2 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (1.17.1)
Requirement already satisfied: skops<1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow) (2.0.49)
Requirement already satisfied: cachetools<8,>=5.0.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (7.1.1)
Requirement already satisfied: click<9,>=7.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (8.3.3)
Requirement already satisfied: cloudpickle<4 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (0.108.0)
Requirement already satisfied: fastapi<1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (0.136.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (3.1.50)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (1.41.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (1.41.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (1.41.1)
Requirement already satisfied: packaging<27 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (6.33.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (2.34.1)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (0.52.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from mlflow-skinny==3.12.0->mlflow) (0.46.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from aiohttp<4->mlflow) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from aiohttp<4->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from aiohttp<4->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from aiohttp<4->mlflow) (1.23.0)
Requirement already satisfied: Mako in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.12)
Requirement already satisfied: cffi>=2.0.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: google-auth~=2.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow) (2.52.0)
Requirement already satisfied: urllib3>=1.26.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from docker<8,>=4.0.0->mlflow) (2.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from fastapi<1->mlflow-skinny==3.12.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from fastapi<1->mlflow-skinny==3.12.0->mlflow) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.12.0->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.12.0->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow) (0.4.2)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.12.0->mlflow) (3.23.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from matplotlib<4->mlflow) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.62b1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.12.0->mlflow) (0.62b1)
Requirement already satisfied: pytz>=2020.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.12.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.12.0->mlflow) (2.46.4)
Requirement already satisfied: six>=1.5 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow) (3.15)
Requirement already satisfied: certifi>=2023.5.7 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow) (2026.4.22)
Requirement already satisfied: joblib>=1.3.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: anyio<5,>=3.6.2 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from starlette<1->mlflow-skinny==3.12.0->mlflow) (4.13.0)
Requirement already satisfied: h11>=0.8 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from uvicorn<1->mlflow-skinny==3.12.0->mlflow) (0.16.0)
Requirement already satisfied: pycparser in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from cffi>=2.0.0->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: wcwidth in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from prettytable>=3.9->skops<1->mlflow) (0.7.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow) (0.6.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [119]:
import mlflow
from mlflow.models import infer_signature
print(mlflow.__version__)

3.12.0

In [120]:
# import libraries
import mlflow
from mlflow.models import infer_signature

In a new terminal, run a local Tracking Server with the following command:

`mlflow server --host 127.0.0.1 --port 8080`

In [121]:
# Set our tracking server uri for logging
mlflow.set_tracking_uri(uri="http://127.0.0.1:8080")

In [122]:
import mlflow

mlflow.set_tracking_uri("file:./mlruns")
print(mlflow.get_tracking_uri())

file:./mlruns

In [123]:
# Create a new MLflow Experiment
mlflow.set_experiment("LR Experiment")

# Start an MLflow run
with mlflow.start_run():
    # Log the hyperparameters
    mlflow.log_params(params)

    # Log the loss metric
    mlflow.log_metric("f1_score", f1_score)

    # Set a tag that we can use to remind ourselves what this run was for
    mlflow.set_tag("Training Info", "Basic LR model to present MLFlow capabilities")

    # Infer the model signature
    signature = infer_signature(X_train, lr.predict(X_train))

    # Log the model
    model_info = mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="bank_model",
        signature=signature,
        input_example=X_train.to_numpy(),
        registered_model_name="bank-model-basic",
    )

/Users/mjhalili/Desktop/EADA_Files/ML_Operations/.venv/lib/python3.14/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2026/05/14 19:34:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/14 19:34:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/14 19:34:07 WARNING mlflow.models.model: Failed to validate serving input example {
  "inputs": [
    [
      34.0,
      0.0,
     .... Alternatively, you can avoid passing input example and pass model signature instead when logging the model. To ensure the input example is valid prior to serving, please try calling `mlflow.models.validate_serving_input` on the model uri and serving input example. A serving input example can be generated from model input example using `mlflow.models.convert_input_example_to_serving_input` function.
Got error: Failed to enforce schema of data '[[  34    0 2679 ...    1    0    0]
 [  31    0  222 ...    1    0    1]
 [  50    0  230 ...    1    1    0]
 ...
 [  44    0   65 ...    1    1    0]
 [  63    0   91 ...    1    1    0]
 [  40    0 1808 ...    1    0    0]]' with schema '['age': long (required), 'default': long (required), 'balance': long (required), 'housing': long (required), 'loan': long (required), 'day': long (required), 'month': long (required), 'duration': long (required), 'campaign': long (required), 'pdays': long (required), 'previous': long (required), 'marital_married': double (required), 'marital_single': double (required), 'job_blue-collar': double (required), 'job_entrepreneur': double (required), 'job_housemaid': double (required), 'job_management': double (required), 'job_retired': double (required), 'job_self-employed': double (required), 'job_services': double (required), 'job_student': double (required), 'job_technician': double (required), 'job_unemployed': double (required), 'job_unknown': double (required), 'education_secondary': double (required), 'education_tertiary': double (required), 'education_unknown': double (required), 'poutcome_other': double (required), 'poutcome_success': double (required), 'poutcome_unknown': double (required), 'contact_telephone': double (required), 'contact_unknown': double (required)]'. Error: Model is missing inputs ['age', 'default', 'balance', 'housing', 'loan', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'marital_married', 'marital_single', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid', 'job_management', 'job_retired', 'job_self-employed', 'job_services', 'job_student', 'job_technician', 'job_unemployed', 'job_unknown', 'education_secondary', 'education_tertiary', 'education_unknown', 'poutcome_other', 'poutcome_success', 'poutcome_unknown', 'contact_telephone', 'contact_unknown']. Note that there were extra inputs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31].
Registered model 'bank-model-basic' already exists. Creating a new version of this model...
Created version '2' of model 'bank-model-basic'.